name: gis-tp2
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - seaborn
    - matplotlib
    - numpy
    - pandas
    - jupyterlab
    - gdal
    - sqlite
    - sqlparse
    - pip
    - pip:
